---
- name: 1. Generate Certificates for Bootstrapping (Localhost)
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cert_dir: "./certs"
    domain_name: "infra.lan"
    vault_san_ips:
      - "{{ vault_vip }}" # vault_vip
      - "{{ ansible_host_mapping.vault1 }}" # vault1
      - "{{ ansible_host_mapping.vault2 }}" # vault2
      - "{{ ansible_host_mapping.vault3 }}" # vault3
    # Dynamically construct the full SAN list
    vault_full_san_list: >-
      {{ [
        "DNS:*." ~ domain_name,
        "DNS:localhost",
        "IP:127.0.0.1"
      ] + (vault_san_ips | map('regex_replace', '^(.*)$', 'IP:\1') | list) }}
  tasks:
    - name: Create certificate directory
      file:
        path: "{{ cert_dir }}"
        state: directory
        mode: '0700'

    - name: Generate Root CA Private Key
      community.crypto.openssl_privatekey:
        path: "{{ cert_dir }}/ca.key"

    - name: Generate Root CA CSR
      community.crypto.openssl_csr:
        path: "{{ cert_dir }}/ca.csr"
        privatekey_path: "{{ cert_dir }}/ca.key"
        common_name: "Vault Root CA"
        basic_constraints: "CA:TRUE"

    - name: Generate Root CA Certificate (Self-Signed)
      community.crypto.x509_certificate:
        path: "{{ cert_dir }}/ca.crt"
        privatekey_path: "{{ cert_dir }}/ca.key"
        csr_path: "{{ cert_dir }}/ca.csr"
        provider: selfsigned

    - name: Generate Vault Wildcard Private Key
      community.crypto.openssl_privatekey:
        path: "{{ cert_dir }}/vault.key"

    - name: Generate Vault Wildcard CSR
      community.crypto.openssl_csr:
        path: "{{ cert_dir }}/vault.csr"
        privatekey_path: "{{ cert_dir }}/vault.key"
        common_name: "*.{{ domain_name }}"
        subject_alt_name: "{{ vault_full_san_list }}"

    - name: Generate Vault Wildcard Certificate (Signed by CA)
      community.crypto.x509_certificate:
        path: "{{ cert_dir }}/vault.crt"
        csr_path: "{{ cert_dir }}/vault.csr"
        provider: ownca
        ownca_path: "{{ cert_dir }}/ca.crt"
        ownca_privatekey_path: "{{ cert_dir }}/ca.key"

- name: 2. Configure Vault Cluster Nodes
  hosts: vault_cluster
  become: yes
  vars:
    cert_dir: "./certs"
  tasks:
    # --- OS Setup ---
    - name: Install EPEL and Dependencies
      dnf:
        name:
          - epel-release
          - yum-utils
          - curl
          - jq
        state: present

    - name: Add HashiCorp Repo
      command: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/hashicorp.repo

    - name: Install Vault and Keepalived
      dnf:
        name:
          - vault
          - keepalived
        state: present

    # --- System Tuning (IPC_LOCK for Vault) ---
    - name: Enable mlock in systemd for Vault
      lineinfile:
        path: /usr/lib/systemd/system/vault.service
        regexp: '^LimitMEMLOCK='
        line: 'LimitMEMLOCK=infinity'
      notify: Reload Systemd

    # [추가된 태스크] Firewalld가 먼저 켜져 있어야 설정을 먹일 수 있습니다.
    - name: Ensure Firewalld is installed and running
      block:
        - name: Install Firewalld (if missing)
          dnf:
            name: firewalld
            state: present
        
        - name: Start and Enable Firewalld Service
          systemd:
            name: firewalld
            state: started
            enabled: yes

    # --- Firewall Setup ---
    - name: Open Firewall Ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 8200/tcp # Vault API
        - 8201/tcp # Vault Cluster
    
    - name: Allow VRRP for Keepalived
      firewalld:
        rich_rule: 'rule protocol value="vrrp" accept'
        permanent: yes
        state: enabled
        immediate: yes

    # --- TLS Distribution ---
    - name: Create Vault TLS directory
      file:
        path: /opt/vault/tls
        state: directory
        owner: vault
        group: vault
        mode: '0750'

    - name: Distribute Certificates
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: vault
        group: vault
        mode: '0640'
      loop:
        - { src: "{{ cert_dir }}/ca.crt", dest: "/opt/vault/tls/ca.crt" }
        - { src: "{{ cert_dir }}/vault.crt", dest: "/opt/vault/tls/vault.crt" }
        - { src: "{{ cert_dir }}/vault.key", dest: "/opt/vault/tls/vault.key" }
      notify: Restart Vault

    - name: Copy CA certificate to system trust anchor
      copy:
        src: "{{ cert_dir }}/ca.crt"
        dest: /etc/pki/ca-trust/source/anchors/vault-ca.crt
        owner: root
        group: root
        mode: '0644'
      register: ca_trust_update

    - name: Update System CA Trust Store
      command: update-ca-trust
      when: ca_trust_update.changed
    # --- Vault Configuration (Raft) ---
    - name: Configure Vault (vault.hcl)
      template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: '0640'
      notify: Restart Vault

    - name: Enable and Start Vault
      systemd:
        name: vault
        enabled: yes
        state: started

    # --- Keepalived Configuration ---
    - name: Configure Keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: Restart Keepalived

    - name: Enable and Start Keepalived
      systemd:
        name: keepalived
        enabled: yes
        state: started

  handlers:
    - name: Reload Systemd
      systemd:
        daemon_reload: yes

    - name: Restart Vault
      systemd:
        name: vault
        state: restarted

    - name: Restart Keepalived
      systemd:
        name: keepalived
        state: restarted
